<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            array( 
                'name' =>  "Caramel Chocolate Coffee",
                'price' => 59.9,
                'image' => "cafe_01",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Large Cold Chocolate Coffee",
                'price' => 49.9,
                'image' => "cafe_02",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Large Cold Chocolate Latte",
                'price' => 54.9,
                'image' => "cafe_03",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Large Cold Chocolate Latte",
                'price' => 54.9,
                'image' => "cafe_04",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Large Cold Chocolate Milkshake",
                'price' => 54.9,
                'image' => "cafe_05",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Small Hot Mocha Coffee",
                'price' => 39.9,
                'image' => "cafe_06",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Large Hot Mocha Coffee with Chocolate",
                'price' => 59.9,
                'image' => "cafe_07",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Large Hot Cappuccino Coffee",
                'price' => 59.9,
                'image' => "cafe_08",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Medium Hot Mocha Coffee",
                'price' => 49.9,
                'image' => "cafe_09",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Medium Cold Caramel Mocha Coffee",
                'price' => 49.9,
                'image' => "cafe_10",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Medium Cold Chocolate Mocha Coffee",
                'price' => 49.9,
                'image' => "cafe_11",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Espresso Coffee",
                'price' => 29.9,
                'image' => "cafe_12",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Large Caramel Cappuccino Coffee",
                'price' => 59.9,
                'image' => "cafe_13",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Large Caramel Coffee",
                'price' => 59.9,
                'image' => "cafe_14",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of 3 Chocolate Donuts",
                'price' => 39.9,
                'image' => "donas_01",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of 3 Glazed Donuts",
                'price' => 39.9,
                'image' => "donas_02",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Strawberry Donut",
                'price' => 19.9,
                'image' => "donas_03",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Chocolate Cookie Donut",
                'price' => 19.9,
                'image' => "donas_04",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Strawberry Flavored Glass Donut",
                'price' => 19.9,
                'image' => "donas_05",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Chocolate Glazed Donut",
                'price' => 19.9,
                'image' => "donas_06",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Chocolate Donut with Extra Chocolate",
                'price' => 19.9,
                'image' => "donas_07",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of 3 Chocolate Donuts",
                'price' => 39.9,
                'image' => "donas_08",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of 3 Vanilla and Chocolate Donuts",
                'price' => 39.9,
                'image' => "donas_09",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of 6 Donuts",
                'price' => 69.9,
                'image' => "donas_10",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of 3 Assorted Donuts",
                'price' => 39.9,
                'image' => "donas_11",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Natural Donut with Chocolate",
                'price' => 19.9,
                'image' => "donas_12",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of 3 Chocolate Chip Donuts",
                'price' => 39.9,
                'image' => "donas_13",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Chocolate and Coconut Donut",
                'price' => 19.9,
                'image' => "donas_14",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of Chocolate Cookies",
                'price' => 29.9,
                'image' => "galletas_01",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of Chocolate and Oat Cookies",
                'price' => 39.9,
                'image' => "galletas_02",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of Vanilla Muffins",
                'price' => 39.9,
                'image' => "galletas_03",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of 4 Oat Cookies",
                'price' => 24.9,
                'image' => "galletas_04",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Assorted Butter Cookies",
                'price' => 39.9,
                'image' => "galletas_05",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Fruity Flavored Cookies",
                'price' => 39.9,
                'image' => "galletas_06",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Single Burger",
                'price' => 59.9,
                'image' => "hamburguesas_01",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Chicken Burger",
                'price' => 59.9,
                'image' => "hamburguesas_02",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Chicken and Chili Burger",
                'price' => 59.9,
                'image' => "hamburguesas_03",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Cheese and Pickle Burger",
                'price' => 59.9,
                'image' => "hamburguesas_04",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Quarter Pounder Burger",
                'price' => 59.9,
                'image' => "hamburguesas_05",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Double Cheeseburger",
                'price' => 69.9,
                'image' => "hamburguesas_06",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Special Hot Dog",
                'price' => 49.9,
                'image' => "hamburguesas_07",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Package of 2 Hot Dogs",
                'price' => 69.9,
                'image' => "hamburguesas_08",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "4 Slices of Cheesecake",
                'price' => 69.9,
                'image' => "pastel_01",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Special Waffle",
                'price' => 49.9,
                'image' => "pastel_02",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "House Croissants",
                'price' => 39.9,
                'image' => "pastel_03",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Cheesecake Slice",
                'price' => 19.9,
                'image' => "pastel_04",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Chocolate Cake",
                'price' => 29.9,
                'image' => "pastel_05",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Chocolate Cake Slice",
                'price' => 29.9,
                'image' => "pastel_06",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Spicy Pizza with Double Cheese",
                'price' => 69.9,
                'image' => "pizzas_01",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Ham and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizzas_02",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Special House Pizza",
                'price' => 69.9,
                'image' => "pizzas_04",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Chorizo Pizza",
                'price' => 69.9,
                'image' => "pizzas_05",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Hawaiian Pizza",
                'price' => 69.9,
                'image' => "pizzas_06",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Bacon Pizza",
                'price' => 69.9,
                'image' => "pizzas_07",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Vegetable and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizzas_08",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Pepperoni and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizzas_09",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Olives and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizzas_10",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'name' =>  "Cheese, Ham, and Mushroom Pizza",
                'price' => 69.9,
                'image' => "pizzas_11",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ];

        DB::table('products')->insert($data);
    }
}
